### ISSUE TITLE
How should we place conference call with pjsip?

### ISSUE THREAD

**Issue by meghaParmar** [petester42/pjsip-ios#10]
I am using pjsip 2.6. Is it possible using pjsip library or any other resources required? Any help will be appreciated.

**Comment by pmairoldi** [comment]
It is possible and I think there are better ways that I did it in 2.6. 

What I had to do I call a second person then connect 2 calls by linking the audio devices together. There is some documentation in the following links. 

http://trac.pjsip.org/repos/wiki/Python_SIP/Media
http://www.pjsip.org/pjmedia/docs/html/group__PJMEDIA__CONF.htm

Sorry can't be more help I don't have access to code I wrote to do conference calls. The main point is to connect all callers together both ways. 

A -> B, B -> A, A-> C, C -> A, C ->B, etc.

**Comment by aanalmehta-sa** [comment]
> It is possible and I think there are better ways that I did it in 2.6.
> 
> What I had to do I call a second person then connect 2 calls by linking the audio devices together. There is some documentation in the following links.
> 
> http://trac.pjsip.org/repos/wiki/Python_SIP/Media
> http://www.pjsip.org/pjmedia/docs/html/group__PJMEDIA__CONF.htm
> 
> Sorry can't be more help I don't have access to code I wrote to do conference calls. The main point is to connect all callers together both ways.
> 
> A -> B, B -> A, A-> C, C -> A, C ->B, etc.

Is there anyway to identify a person who left the call? 
As far as I understand, Pjsip works based on port info and connection bridge. I have successfully merged my call with earch other. But now what I want is if one of them left the call then how to identify other user about that event?

**Comment by pmairoldi** [comment]
I have no idea
