### ISSUE TITLE
hi in this example where i have to configure my sip details and how to call please send me sample code 

### ISSUE THREAD

**Issue by SURENDRA7700** [petester42/pjsip-ios#9]

**Comment by pmairoldi** [comment]
This might help you. https://github.com/eofster/Telephone

**Comment by SURENDRA7700** [comment]
Thank you for sending Telephone.
NOW I am developing sip application for I phone can you please send me
sample code for sip-voip application

**Comment by pmairoldi** [comment]
The pjsip documentation should be enough. The code for iOS will be very similar to Telephone. The only difference will be the UI.
